/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Hora;
import javax.swing.JOptionPane;

/**
 *
 * @author pared
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form pRINCIPAK
     */
    Hora h;
    public Principal() {
        initComponents();
        cmbIgual.setEnabled(false);
        cmbInicializar.setEnabled(true);
        cmbMayorQue.setEnabled(false);
        cmbMenorQue.setEnabled(false);
        cmbMostrar.setEnabled(false);
        cmbValidarHora1.setEnabled(false);
        cmbValidarHora2.setEnabled(false);
        cmbReiniciar.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHora1 = new javax.swing.JTextField();
        txtMinutos1 = new javax.swing.JTextField();
        txtSegundos1 = new javax.swing.JTextField();
        txtHora2 = new javax.swing.JTextField();
        txtMinutos2 = new javax.swing.JTextField();
        txtSegundos2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbValidarHora1 = new javax.swing.JButton();
        cmbValidarHora2 = new javax.swing.JButton();
        cmbMostrar = new javax.swing.JButton();
        cmbIgual = new javax.swing.JButton();
        cmbInicializar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbMayorQue = new javax.swing.JButton();
        cmbMenorQue = new javax.swing.JButton();
        cmbReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("HORAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        txtHora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora1KeyTyped(evt);
            }
        });
        jPanel1.add(txtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 30, -1));

        txtMinutos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos1KeyTyped(evt);
            }
        });
        jPanel1.add(txtMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 30, -1));

        txtSegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos1KeyTyped(evt);
            }
        });
        jPanel1.add(txtSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 30, -1));

        txtHora2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora2KeyTyped(evt);
            }
        });
        jPanel1.add(txtHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 30, -1));

        txtMinutos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos2KeyTyped(evt);
            }
        });
        jPanel1.add(txtMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 30, -1));

        txtSegundos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos2KeyTyped(evt);
            }
        });
        jPanel1.add(txtSegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 30, -1));

        jLabel2.setText(":");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 20));

        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TIEMPO1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TIEMPO2:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 20));

        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        cmbValidarHora1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbValidarHora1.setText("Validar Hora1");
        cmbValidarHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValidarHora1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbValidarHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, -1));

        cmbValidarHora2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbValidarHora2.setText("Validar Hora2");
        cmbValidarHora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValidarHora2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbValidarHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 130, -1));

        cmbMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbMostrar.setText("Mostrar");
        cmbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 110, -1));

        cmbIgual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbIgual.setText("Igual");
        cmbIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIgualActionPerformed(evt);
            }
        });
        jPanel1.add(cmbIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 110, -1));

        cmbInicializar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbInicializar.setText("Inicializar");
        cmbInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbInicializarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbInicializar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 130, -1));

        txtMostrar.setEditable(false);
        txtMostrar.setColumns(20);
        txtMostrar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 250, 120));

        jLabel8.setText("H");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel9.setText("M");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel10.setText("S");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel11.setText("H");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel12.setText("M");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel13.setText("S");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        cmbMayorQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbMayorQue.setText("Mayor Que");
        cmbMayorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMayorQueActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMayorQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 110, -1));

        cmbMenorQue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbMenorQue.setText("Menor Que");
        cmbMenorQue.setActionCommand("Menor Que");
        cmbMenorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenorQueActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMenorQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 110, -1));

        cmbReiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbReiniciar.setText("Reiniciar");
        cmbReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(cmbReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbValidarHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValidarHora1ActionPerformed
        // TODO add your handling code here:
        int hora1, minuto1, segundo1;
        if (txtHora1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la hora del tiempo1", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtHora1.requestFocusInWindow();
        }
        else if (txtMinutos1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el minuto del tiempo1", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMinutos1.requestFocusInWindow();
        }
        else if (txtSegundos1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el segundo del tiempo1", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSegundos1.requestFocusInWindow();
        }
        else 
        {
        hora1= Integer.parseInt(txtHora1.getText());
        minuto1= Integer.parseInt(txtMinutos1.getText());
        segundo1= Integer.parseInt(txtSegundos1.getText());
        h = new Hora (hora1, minuto1, segundo1);
       JOptionPane.showMessageDialog(this, ""+h.Validar());
        }
        
        cmbIgual.setEnabled(true);
        cmbInicializar.setEnabled(false);
        cmbMayorQue.setEnabled(true);
        cmbMenorQue.setEnabled(true);
        cmbMostrar.setEnabled(true);
        cmbReiniciar.setEnabled(true);
        cmbValidarHora1.setEnabled(false);
        cmbValidarHora2.setEnabled(true);
        
    }//GEN-LAST:event_cmbValidarHora1ActionPerformed

    private void cmbValidarHora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValidarHora2ActionPerformed
        // TODO add your handling code here:
        int hora2, minuto2, segundo2;
        String aux, aux2;
        
        if (txtHora2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la hora del tiempo2", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtHora2.requestFocusInWindow();
        }
        else if (txtMinutos2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el minuto del tiempo2", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMinutos2.requestFocusInWindow();
        }
        else if (txtSegundos2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese el segundo del tiempo2", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtSegundos2.requestFocusInWindow();
        }
        else 
        {
        hora2= Integer.parseInt(txtHora2.getText());
        minuto2= Integer.parseInt(txtMinutos2.getText());
        segundo2 = Integer.parseInt(txtSegundos2.getText());
       
        JOptionPane.showMessageDialog(this, ""+ h.Validar2(hora2, minuto2, segundo2));
        }
        
        cmbIgual.setEnabled(true);
        cmbInicializar.setEnabled(false);
        cmbMayorQue.setEnabled(true);
        cmbMenorQue.setEnabled(true);
        cmbMostrar.setEnabled(true);
        cmbReiniciar.setEnabled(true);
        cmbValidarHora1.setEnabled(false);
        cmbValidarHora2.setEnabled(false);
    }//GEN-LAST:event_cmbValidarHora2ActionPerformed

    private void cmbIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIgualActionPerformed
        // TODO add your handling code here:
        int hora1, minuto1, segundo1, hora2, minuto2, segundo2;
        String aux, aux2;
        hora1= Integer.parseInt(txtHora1.getText());
        minuto1= Integer.parseInt(txtMinutos1.getText());
        segundo1= Integer.parseInt(txtSegundos1.getText());
        
        hora2= Integer.parseInt(txtHora2.getText());
        minuto2= Integer.parseInt(txtMinutos2.getText());
        segundo2 = Integer.parseInt(txtSegundos2.getText());
        
        JOptionPane.showMessageDialog(this, ""+h.Igual(hora2, minuto2, segundo2));
        
    }//GEN-LAST:event_cmbIgualActionPerformed

    private void cmbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarActionPerformed
        // TODO add your handling code here:
        String mostrar;
        int hora2, minuto2, segundo2;
        
        hora2= Integer.parseInt(txtHora2.getText());
        minuto2= Integer.parseInt(txtMinutos2.getText());
        segundo2 = Integer.parseInt(txtSegundos2.getText());
        
        mostrar = h.Mostrar(hora2, minuto2, segundo2);
        txtMostrar.append(mostrar);
    }//GEN-LAST:event_cmbMostrarActionPerformed

    private void cmbInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInicializarActionPerformed
        // TODO add your handling code here:
        h = new Hora ();
        
        txtHora1.setText(""+h.getHoras());
        txtHora2.setText(""+h.getHoras());
        txtMinutos1.setText(""+h.getMinutos());
        txtMinutos2.setText(""+h.getMinutos());
        txtSegundos1.setText(""+h.getSegundos());
        txtSegundos2.setText(""+h.getSegundos());
         
       cmbInicializar.setEnabled(true);
       cmbIgual.setEnabled(false);
       cmbMayorQue.setEnabled(false);
       cmbMenorQue.setEnabled(false);
       cmbMostrar.setEnabled(false);
       cmbValidarHora1.setEnabled(true);
       cmbValidarHora2.setEnabled(true);
    }//GEN-LAST:event_cmbInicializarActionPerformed

    private void cmbMayorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMayorQueActionPerformed
        // TODO add your handling code here:
        int hora1, minuto1, segundo1, hora2, minuto2, segundo2;
        String aux, aux2;
        hora1= Integer.parseInt(txtHora1.getText());
        minuto1= Integer.parseInt(txtMinutos1.getText());
        segundo1= Integer.parseInt(txtSegundos1.getText());
        
        hora2= Integer.parseInt(txtHora2.getText());
        minuto2= Integer.parseInt(txtMinutos2.getText());
        segundo2 = Integer.parseInt(txtSegundos2.getText());
        
        JOptionPane.showMessageDialog(this, ""+h.MayorQue(hora2, minuto2, segundo2));
    }//GEN-LAST:event_cmbMayorQueActionPerformed

    private void cmbMenorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenorQueActionPerformed
        // TODO add your handling code here:
        int hora1, minuto1, segundo1, hora2, minuto2, segundo2;
        String aux, aux2;
        hora1= Integer.parseInt(txtHora1.getText());
        minuto1= Integer.parseInt(txtMinutos1.getText());
        segundo1= Integer.parseInt(txtSegundos1.getText());
        
        hora2= Integer.parseInt(txtHora2.getText());
        minuto2= Integer.parseInt(txtMinutos2.getText());
        segundo2 = Integer.parseInt(txtSegundos2.getText());
        
        JOptionPane.showMessageDialog(this, ""+h.MenorQue(hora2, minuto2, segundo2));
       
    }//GEN-LAST:event_cmbMenorQueActionPerformed

    private void txtHora1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtHora1KeyTyped

    private void txtMinutos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMinutos1KeyTyped

    private void txtSegundos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSegundos1KeyTyped

    private void txtHora2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtHora2KeyTyped

    private void txtMinutos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMinutos2KeyTyped

    private void txtSegundos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSegundos2KeyTyped

    private void cmbReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReiniciarActionPerformed
        // TODO add your handling code here:
        cmbIgual.setEnabled(false);
        cmbInicializar.setEnabled(true);
        cmbMayorQue.setEnabled(false);
        cmbMenorQue.setEnabled(false);
        cmbMostrar.setEnabled(false);
        cmbReiniciar.setEnabled(false);
        cmbValidarHora1.setEnabled(false);
        cmbValidarHora2.setEnabled(false);
    }//GEN-LAST:event_cmbReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbIgual;
    private javax.swing.JButton cmbInicializar;
    private javax.swing.JButton cmbMayorQue;
    private javax.swing.JButton cmbMenorQue;
    private javax.swing.JButton cmbMostrar;
    private javax.swing.JButton cmbReiniciar;
    private javax.swing.JButton cmbValidarHora1;
    private javax.swing.JButton cmbValidarHora2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    private javax.swing.JTextField txtMinutos1;
    private javax.swing.JTextField txtMinutos2;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtSegundos1;
    private javax.swing.JTextField txtSegundos2;
    // End of variables declaration//GEN-END:variables
}
